#!/bin/bash                                                                                                                                                

#SBATCH -J cut_modification                                                                                                                                

#SBATCH --time=5:00:00                                                                                                                                     

#SBATCH --cpus-per-task=1                                                                                                                                  

#SBATCH --mem=5000                                                                                                                                         

#SBATCH -A mrc-bsu-sl2-cpu                                                                                                                                 

#SBATCH -p icelake                                                                                                                                         

#SBATCH --array=1-100%250                                                                                                                                 


## MODULES                                                                                                                                                 

. /etc/profile.d/modules.sh              # Leave this line (enables the module command)                                                                    
module purge                            # Removes all modules still loaded                                                                                 
module load rhel8/default-icl           # REQUIRED - loads the basic environment                                                                           

# Load the latest R version.                                                                                                                               
module load R/4.3.1-icelake


## RUN                                                                                                                                                     

CMD="Rscript simulation_scipt.R"





###############################################################                                                                                            
### You should not have to change anything below this line ####                                                                                            
###############################################################                                                                                            

JOBID=$SLURM_JOB_ID

echo -e "JobID: $JOBID\n======"
echo "Time: `date`"
if [ $SLURM_JOB_NUM_NODES -gt 1 ]; then
        echo "Running on nodes: $SLURM_JOB_NODELIST"
else
        echo "Running on node: `hostname`"
fi

echo "Current directory: `pwd`"
echo -e "\nNum tasks = $SLURM_NTASKS, Num nodes = $SLURM_JOB_NUM_NODES, OMP_NUM_THREADS = $OMP_NUM_THREADS"
echo -e "\nExecuting command:\n==================\n$CMD\n"

eval $CMD
